import Config

# Para el desarrollo, desactivamos cualquier caché y activamos
# la depuración y la recarga de código.
#
# La configuración de los observadores se puede utilizar para ejecutar
# observadores externos a la aplicación. Por ejemplo, podemos usarla
# para empaquetar archivos fuente .js y .css.
config :trivia_crack_quiz, TriviaCrackQuizWeb.Endpoint,
  # Escucha en todas las interfaces para que otras maquinas de la red local
  # puedan entrar con http://IP_DEL_HOST:4000. Volver a {127, 0, 0, 1} para
  # restringir el acceso solo a esta maquina.
  http: [ip: {0, 0, 0, 0}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "08m4OC7gAV+QeNoYrNB2wTP9TzB0zpm0qSxsdfePHEKXCa2qGlIBbseInihtWPgt",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:trivia_crack_quiz, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:trivia_crack_quiz, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :trivia_crack_quiz, TriviaCrackQuizWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$",
      # Gettext translations
      ~r"priv/gettext/.*\.po$",
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/trivia_crack_quiz_web/router\.ex$",
      ~r"lib/trivia_crack_quiz_web/(controllers|live|components)/.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :trivia_crack_quiz, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true
